"""Numerical regression tests for the MARMIT-1/MARMIT-2 soil model ports,
vs. reference values generated by running ToolsRTM::get.marmit.rsoil() in R
(see python/scratch/scratch_export_marmit.py/python/scratch/scratch_export_marmit2.R for
the bundled-data/reference-case export and python/README.md for exact
scope).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import get_marmit_rsoil

REFDATA = Path(__file__).parent / "refdata"


def test_get_marmit_rsoil_matches_r():
    ref = pd.read_csv(REFDATA / "ref_marmit.csv")
    out = get_marmit_rsoil(soil_id=1, L=0.05, eps=0.3, wl_out=np.arange(400, 2501))
    np.testing.assert_allclose(out.wavelength, ref["wavelength"].to_numpy())
    np.testing.assert_allclose(out.rsoil_dry, ref["rsoil_dry"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(out.rsoil_wet, ref["rsoil_wet"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(out.smc, 26.72598, rtol=1e-4)


def test_get_marmit2_rsoil_matches_r():
    ref = pd.read_csv(REFDATA / "ref_marmit2.csv")
    out = get_marmit_rsoil(
        soil_id=1, L=0.05, eps=0.3, version="marmit2", n_i=1.53, k_i=0.001, d_i=0.0005,
        wl_out=np.arange(400, 2501),
    )
    np.testing.assert_allclose(out.wavelength, ref["wavelength"].to_numpy())
    np.testing.assert_allclose(out.rsoil_dry, ref["rsoil_dry"].to_numpy(), rtol=1e-6)
    # exp1(x): R integrates numerically (stats::integrate), scipy.special.exp1
    # uses a rational/continued-fraction approximation -- two different
    # numerical methods for the same function, hence the looser tolerance
    # than the rest of this port (still ~1e-6 relative in practice).
    np.testing.assert_allclose(out.rsoil_wet, ref["rsoil_wet"].to_numpy(), rtol=1e-5)
    np.testing.assert_allclose(out.smc, 26.72598, rtol=1e-4)


def test_wet_never_brighter_than_dry():
    out = get_marmit_rsoil(soil_id=1, L=0.05, eps=0.5)
    assert np.all(out.rsoil_wet <= out.rsoil_dry + 1e-9)


def test_marmit2_wet_never_brighter_than_dry():
    out = get_marmit_rsoil(soil_id=1, L=0.05, eps=0.5, version="marmit2")
    assert np.all(out.rsoil_wet <= out.rsoil_dry + 1e-9)
