
#' \code{get.outs.lut} get the outputs from SCOPE model. This code is for a LUT of simulations
#'
#' @param data.sim  list elements generated by the SCOPE model
#' @param LUT a list of inputs used in the SCOPE model
#' @param path.out  path for saving the main files
#' @param get.plots  is true, intermediate plots will be generated in Plot folder
#' @param get.outputs If get.outputs = 'ALL', all variables will be retrieved; if get.outputs = 'Main', only the main variables will be retrieved.
#' By default, SCOPE uses get.outputs = 'ALL', for processing a huge LUT, it is recommended to use get.outputs = 'Main'.
#' @param nSamples number of LUT samples to process; used to size progress reporting for the extraction loop.

#' @author Carlos Camino (Ported version into R)
#'
#' @examples
#' \dontrun{
#' nSamples <- 100
#' get.outs.lut.v2(data.sim = LUT, LUT = LUT, path.out = path.out, get.plots = TRUE,
#'                  get.outputs = 'ALL', nSamples = nSamples)
#' }

get.outs.lut.v2 <-function(data.sim, LUT,path.out,get.plots, get.outputs,nSamples){

  #if (!require("data.table")) { install.packages("data.table"); require("data.table") }  ### hsdar for PROSAIL

  # Get the current system time
  current_time <- format(Sys.time(), "%Y-%m-%d_%H-%M-%S")





  if (missing(get.plots)){
    get.plots = FALSE
  }


  if (missing(path.out)) {
    path_outs <- 'outs/'
    message('outs/ folder will be used for the SCOPE outputs')

  } else {

    path_outs <- path.out

  }

  # BUG (fixed): every folder_out/folder_for_plots/folder_out_parameters
  # path below is built with paste(path_outs, current_time, ..., sep = "")
  # -- i.e. plain string concatenation, not file.path(). If the caller's
  # path.out doesn't happen to end in "/" (e.g. path.out = "outs/run1", a
  # perfectly normal way to specify a path), the timestamp gets appended
  # directly onto the last path component instead of nested inside it,
  # silently creating a sibling directory with a mangled name (e.g.
  # "outs/run12026-08-05_17-37-40") instead of "outs/run1/2026-08-05_17-37-40"
  # -- no error, just scattered/mislocated output that later "most recent
  # folder" lookups (list.dirs() + tail()) never find. Normalizing path_outs
  # to always end in "/" BEFORE any of those paste() calls fixes it for
  # every path built below regardless of what the caller passed in. Must
  # happen before the dir.create()/folder_out block below, not after.
  if (!grepl("[\\\\/]$", path_outs)) {
    path_outs <- paste0(path_outs, "/")
  }

  if (!dir.exists(path_outs)) {
    dir.create(path_outs)
  }

  # Create a folder with the current system time as part of the folder name
  folder_out <- paste(path_outs, current_time, sep = "")
  dir.create(folder_out)

  if (get.plots == T) {
    folder_for_plots <- paste(path_outs, current_time,'/Plots/', sep = "")
    dir.create(folder_for_plots)
  }

  if (missing(get.outputs)){
    get.outputs = 'ALL'
    message('All parameteres will be saved ...')

  } else {
    get.outputs = get.outputs
    message('Main  parameteres will be saved ...')

  }


  # Create a folder with the current system time as part of the folder name
  folder_out_parameters <- paste(path_outs, current_time,'/Parameters/', sep = "")
  dir.create(folder_out_parameters)

  message <- "the SCOPE model uses the version 2.1 integrated in the SCOPEinR package "
  file_readme <-paste(folder_out_parameters,"/SCOPEversion.txt",sep='')
  writeLines(message, file_readme)
  # save using data.table
  data.table::fwrite(LUT, paste(folder_out_parameters,"/inputLUT.csv",sep=''))


  ##############################################################################################################################
  # 1.1 Get Reflectance ----
  ##############################################################################################################################

  n.sim<-length(data.sim)
  wlS <- data.sim[[1]]$data.spectral$wlS[1:2001]

  if (get.outputs == 'Main'){

    matrix.reflapp <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$reflapp[1:2001])
    matrix.refl <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$refl[1:2001])

    # save using data.table
    data.table::fwrite(data.frame(t(matrix.refl)), paste(folder_out,"/refl.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.reflapp)), paste(folder_out,"/reflapp.csv",sep=''))


  } else if (get.outputs == 'ALL'){

    matrix.rsd <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$rsd[1:2001])
    matrix.rso <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$rso[1:2001])
    matrix.rdd <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$rdd[1:2001])
    matrix.rdo <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$rdo[1:2001])
    matrix.reflapp <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$reflapp[1:2001])
    matrix.refl <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$refl[1:2001])


    # save using data.table
    data.table::fwrite(data.frame(t(matrix.rsd)), paste(folder_out,"/rsd.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.rso)), paste(folder_out,"/rso.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.rdd)), paste(folder_out,"/rdd.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.rdo)), paste(folder_out,"/rdo.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.refl)), paste(folder_out,"/refl.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.reflapp)), paste(folder_out,"/reflapp.csv",sep=''))

  }


  if (get.plots == T) {

    # get the rows for plotting

    if (ncol(matrix.refl) >= 100){
      ## select rows
      n.cols <- 50
      cols.selected <- sample(ncol(matrix.refl), n.cols)


    } else {
      ## select rows
      n.cols <- 5
      cols.selected <- 1:ncol(matrix.refl)
    }

    if (get.outputs == 'ALL'){

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.1 Get rdo ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_rdo <-as.data.frame(matrix.rdo[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_rdo
      df_rdo$wave <- rep(wave, nrow(df_rdo) / length(wave))

      # Plot all spectra in a single plot
      plot.rdo<-ggplot(df_rdo, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (rdo)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_rdo.png',sep=''),plot=plot.rdo,
             width = 10, height = 10,  dpi = 300,units = "cm")

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.2 Get rdd ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_rdd <-data.frame(matrix.rdd[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_rdd
      df_rdd$wave <- rep(wave, nrow(df_rdd) / length(wave))

      # Plot all spectra in a single plot
      plot.rdd<-ggplot(df_rdd, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (rdd)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_rdd.png',sep=''),plot=plot.rdd,
             width = 10, height = 10,  dpi = 300,units = "cm")


      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.3 Get rso ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_rso <-data.frame(matrix.rso[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_rso
      df_rso$wave <- rep(wave, nrow(df_rso) / length(wave))

      # Plot all spectra in a single plot
      plot.rso<-ggplot(df_rso, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (rso)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_rso.png',sep=''),plot=plot.rso,
             width = 10, height = 10,  dpi = 300,units = "cm")


      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.4 Get rsd ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_rsd <-data.frame(matrix.rsd[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_rsd
      df_rsd$wave <- rep(wave, nrow(df_rsd) / length(wave))


      # Plot all spectra in a single plot
      plot.rsd<-ggplot(df_rsd, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (rsd)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_rsd.png',sep=''),plot=plot.rsd,
             width = 10, height = 10,  dpi = 300,units = "cm")

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.5 Get refl  ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_refl <-data.frame(matrix.refl[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_refl
      df_refl$wave <- rep(wave, nrow(df_refl) / length(wave))

      # Plot all spectra in a single plot
      plot.refl<-ggplot(df_refl, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (refl)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_refl.png',sep=''),plot=plot.refl,
             width = 10, height = 10,  dpi = 300,units = "cm")

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.6 Get reflapp ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      # Reshape the data frame into a long format
      df_reflapp <-data.frame(matrix.reflapp[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to plot.reflapp
      df_reflapp$wave <- rep(wave, nrow(df_reflapp) / length(wave))

      # Plot all spectra in a single plot
      plot.reflapp<-ggplot(df_reflapp, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Apparent reflectance") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflappectance_reflapp.png',sep=''),plot=plot.reflapp,
             width = 10, height = 10,  dpi = 300,units = "cm")

    } else {

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.5 Get refl  ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_refl <-data.frame(matrix.refl[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to df_refl
      df_refl$wave <- rep(wave, nrow(df_refl) / length(wave))

      # Plot all spectra in a single plot
      plot.refl<-ggplot(df_refl, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Reflectance (refl)") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflectance_refl.png',sep=''),plot=plot.refl,
             width = 10, height = 10,  dpi = 300,units = "cm")

      # :::::::::::::::::::::::::::::::::::::::::::::
      # 1.6 Get reflapp ----
      # :::::::::::::::::::::::::::::::::::::::::::::

      # Reshape the data frame into a long format
      df_reflapp <-data.frame(matrix.reflapp[,cols.selected]) %>%
        gather(n.sim, value)

      wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
      # Add wave column to plot.reflapp
      df_reflapp$wave <- rep(wave, nrow(df_reflapp) / length(wave))

      # Plot all spectra in a single plot
      plot.reflapp<-ggplot(df_reflapp, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
        geom_line(linewidth = 0.5) +
        theme_bw() +
        xlim(400, 2499) +
        ylab("Apparent reflectance") +
        theme(legend.position = "none") +
        guides(color = guide_legend(title = NULL))
      ggsave(paste(folder_for_plots,'1-reflappectance_reflapp.png',sep=''),plot=plot.reflapp,
             width = 10, height = 10,  dpi = 300,units = "cm")
    }


  }


  ##############################################################################################################################
  # 1.2 Get Irradiance ----
  ##############################################################################################################################


  if (get.outputs == 'ALL'){

    matrix.Esun <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Esun_[1:2001])
    matrix.Esky <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Esky_[1:2001])

    # save using data.table
    data.table::fwrite(data.frame(t(matrix.Esun)), paste(folder_out,"/Esun.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.Esky)), paste(folder_out,"/Esky.csv",sep=''))
  }


  if (get.plots == T & get.outputs == 'ALL' ) {


    # Create the df.irrad data frame
    df.irrad <- data.frame(wave = wave,
                           Esun_ = matrix.Esun[,1],
                           Esky_ = matrix.Esky[,1])


    wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
    # Add wave column to df.irrad
    df.irrad$wave <- wave

    p.irrad<- ggplot(data = df.irrad, aes(x = wave)) +
      geom_line(aes(y = Esun_, color = 'Esun_'), linewidth = 0.5) +
      geom_line(aes(y = Esky_, color = 'Esky_'), linewidth = 0.5) +

      scale_color_manual(name = 'Irradiance',
                         values = c('Esun_' = 'orange',
                                    'Esky_' ='grey')) +

      theme_bw() + xlim(400,2499) +
      theme(legend.position = "top") +ylab("Irradiance") +
      guides(color = guide_legend(title = NULL))

    ggsave(paste(folder_for_plots,'2-Irradiance.png',sep=''),plot=p.irrad,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }

  ##############################################################################################################################
  # 1.3 Get Radiance spectrum  excluding/adding fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################

  wlS <- data.sim[[1]]$data.spectral$wlS[1:2001]

  if (get.outputs == 'ALL'){

    matrix.Lotot <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Lotot_[1:2001])
    matrix.Lototf <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Lototf_[1:2001])

    # save using data.table
    data.table::fwrite(data.frame(t(matrix.Lotot)), paste(folder_out,"/Lo_spectrum.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.Lototf)), paste(folder_out,"/Lo_spectrum_includingF.csv",sep=''))
  }


  if (get.plots == T & get.outputs == 'ALL') {

    # get the rows for plotting

    if (ncol(matrix.Lotot) >= 100){
      ## select rows
      n.cols <- 50
      cols.selected <- sample(ncol(matrix.Lotot), n.cols)


    } else {
      ## select rows
      n.cols <- 5
      cols.selected <- 1:ncol(matrix.Lotot)
    }

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get Lotot_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Lotot_ <-data.frame(matrix.Lotot[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
    # Add wave column to df_Lotot_
    df_Lotot_$wave <- rep(wave, nrow(df_Lotot_) / length(wave))

    # Plot all spectra in a single plot
    plot.Lotot_<-ggplot(df_Lotot_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 900) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'3-Radiance_excluding_Fluorescence.png',sep=''),plot=plot.Lotot_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get Lototf_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Lototf_ <-data.frame(matrix.Lototf[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- data.sim[[1]]$data.spectral$wlS[1:2001]
    # Add wave column to df_Lototf_
    df_Lototf_$wave <- rep(wave, nrow(df_Lototf_) / length(wave))


    # Plot all spectra in a single plot
    plot.Lototf_<-ggplot(df_Lototf_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 900) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'3-Radiance_adding_Fluorescence.png',sep=''),plot=plot.Lototf_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }



  ##############################################################################################################################
  # 1.4 Get Radiation  ----
  ##############################################################################################################################

  matrix.radiation<- matrix(nrow = length(data.sim), ncol = 5)


  for (i in 1:length(data.sim)) {

    # Add radiation data
    n.sim <-i
    Rin <- data.sim[[i]]$data.meteo$Rin
    Rli <- data.sim[[i]]$data.meteo$Rli
    Eouto <- data.sim[[i]]$data.rad$Eouto
    Eoutte <- data.sim[[i]]$data.rad$Eoutte

    matrix.radiation[i,] <- c(n.sim,Rin,Rli,Eouto,Eoutte)

  }


  df.radiation<- as.data.frame(matrix.radiation)
  # Set column names as n1, n2, n3, ...
  colnames(df.radiation) <- c('n.sim','ShortIn','ShortLong','HemisOutIn','HemisOutLong')
  # save using data.table
  data.table::fwrite(df.radiation, paste(folder_out,"/radiation.csv",sep=''))


  df.radiation.units <- data.frame(ShortIn = 'W m-2', ShortLong = 'W m-2',
                                   HemisOutIn = 'W m-2', HemisOutLong = 'W m-2',
                                   Lo = 'W m-2 sr -1', Lot = 'W m-2 sr -1', Lote = 'W m-2 sr -1')


  # save using data.table
  data.table::fwrite(df.radiation.units, paste(folder_out,"/radiation_units.csv",sep=''))


  ##############################################################################################################################
  # 1.5 Get ApAR values  ----
  ##############################################################################################################################



  matrix.apar<- matrix(ncol = 23, nrow = length(data.sim))

  for (i in 1:length(data.sim)) {

    # Add number of sim
    n.sim <- i

    # EPAR and PAR
    iPAR =  data.sim[[i]]$data.rad[['PAR']] ## units in umol m-2 s-1
    iPARE =  data.sim[[i]]$data.rad[['EPAR']] ## units in W m-2
    ## LAI sunit/sgaded
    LAIsunlit =  data.sim[[i]]$data.canopy[['LAIsunlit']] ## m2 m-2
    LAIshaded =  data.sim[[i]]$data.canopy[['LAIshaded']] ## m2 m-2
    # Total aPAR
    aPARTot =  data.sim[[i]]$data.canopy[['Pntot']] ## units in umol m-2 s-1
    aPARTotSun =  data.sim[[i]]$data.canopy[['Pnsun']] ## units in umol m-2 s-1
    aPARTotShaded =  data.sim[[i]]$data.canopy[['Pnsha']] ## units in umol m-2 s-1

    ## Total aPAR Cab
    aPARCabTot =  data.sim[[i]]$data.canopy[['Pntot_Cab']] ## units in umol m-2 s-1
    aPARCabSun =  data.sim[[i]]$data.canopy[['Pnsun_Cab']] ## units in umol m-2 s-1
    aPARCabShaded =  data.sim[[i]]$data.canopy[['Pnsha_Cab']] ## units in umol m-2 s-1

    ## Total aPAR Car
    aPARCarTot =  data.sim[[i]]$data.canopy[['Pntot_Car']] ## units in umol m-2 s-1
    aPARCarSun =  data.sim[[i]]$data.canopy[['Pnsun_Car']] ## units in umol m-2 s-1
    aPARCarShaded =  data.sim[[i]]$data.canopy[['Pnsha_Car']] ## units in umol m-2 s-1

    # Total aPAR E
    aPARTotE =  data.sim[[i]]$data.canopy[['Rntot_PAR']] ## units in W m-2
    aPARTotSunE =  data.sim[[i]]$data.canopy[['Rnsun_PAR']] ##  units in W m-2
    aPARTotShadedE =  data.sim[[i]]$data.canopy[['Rnsha_PAR']] ## units in m-2

    # Total aPAR E Cab
    aPARTotCabE =  data.sim[[i]]$data.canopy[['Rntot_Cab']] ## units in W m-2
    aPARTotSunCabE =  data.sim[[i]]$data.canopy[['Rnsun_Car']]##  units in W m-2
    aPARTotShadedCabE =  data.sim[[i]]$data.canopy[['Rnsha_Car']] ## units in W m-2

    # Total aPAR E Car
    aPARTotCarE =  data.sim[[i]]$data.canopy[['Rntot_Car']] ## units in W m-2
    aPARTotSunCarE =  data.sim[[i]]$data.canopy[['Rnsun_Car']] ##  units in W m-2
    aPARTotShadedCarE =  data.sim[[i]]$data.canopy[['Rnsha_Car']]## units in W m-2

    data.apar <-cbind(n.sim, iPAR, iPARE,
          LAIsunlit, LAIshaded,
          aPARTot, aPARTotSun, aPARTotShaded,
          aPARCabTot, aPARCabSun, aPARCabShaded,
          aPARCarTot, aPARCarSun, aPARCarShaded,
          aPARTotE, aPARTotSunE, aPARTotShadedE,
          aPARTotCabE, aPARTotSunCabE, aPARTotShadedCabE,
          aPARTotCarE, aPARTotSunCarE,aPARTotShadedCarE)
    matrix.apar[i,] <- data.apar

  }

  df.apar<- as.data.frame(matrix.apar)

  # Set column names as n1, n2, n3, ...
  colnames(df.apar) <- c('n.sim','iPAR','iPARE',
                         'LAIsunlit','LAIshaded',
                         'aPARTot','aPARTotSun','aPARTotShaded',
                         'aPARCabTot','aPARCabSun','aPARCabShaded',
                          'aPARCarTot','aPARCarSun','aPARCarShaded',
                         'aPARTotE','aPARTotSunE','aPARTotShadedE',
                         'aPARTotCabE','aPARTotSunCabE','aPARTotShadedCabE','aPARTotCarE',
                         'aPARTotSunCarE','aPARTotShadedCarE')

  # save using data.table
  data.table::fwrite(df.apar, paste(folder_out,"/aPAR.csv",sep=''))

  ##############################################################################################################################
  # 1.6 Get resistance values  ----
  ##############################################################################################################################

  matrix.resistance<- matrix(ncol = 5, nrow = length(data.sim))

  for (i in 1:length(data.sim)) {
    # Add number of sim
    n.sim <- i
    ra = data.sim[[i]]$resist_out[['raws']] ## units in s m-1
    raforSoil = data.sim[[i]]$resist_out[['rss']] ## units in s m-1
    rss = data.sim[[i]]$resist_out[['rss']] ## units in s m-1
    ustar = data.sim[[i]]$resist_out[['ustar']] ## units in m2 s-1

    data.resistance <-cbind(n.sim, ra, raforSoil,rss,ustar)
    matrix.resistance[i,] <- data.resistance

  }
  df.resistance <- as.data.frame(matrix.resistance)

  # Set column names as n1, n2, n3, ...
  colnames(df.resistance) <- c('n.sim','raws','raforSoil','rss','ustar')

  # save using data.table
  data.table::fwrite(df.resistance, paste(folder_out,"/resistance.csv",sep=''))

  df.resistance.units <-data.frame(ra = 's m-1', raforSoil = 's m-1',
                                   rss = 's m-1', ustar ='m2 s-1')

  # save using data.table
  data.table::fwrite(df.resistance.units, paste(folder_out,"/resistance_units.csv",sep=''))

  ##############################################################################################################################
  # 1.7 Get vegetation values  ----
  ##############################################################################################################################


  matrix.vegetation<- matrix(ncol = 7, nrow = length(data.sim))

  for (i in 1:length(data.sim)) {

    # Add number of sim
    n.sim <- i
    Photosintesis = data.sim[[i]]$data.canopy[['A']] ## units in umol m-2 s-1
    Electron_transport = data.sim[[i]]$data.canopy[['Ja']] ## units in umol m-2 s-1
    NPQ_energy = data.sim[[i]]$data.canopy[['ENPQ']] ## units in W m-2
    NPQ_photon = data.sim[[i]]$data.canopy[['PNPQ']] ## units in umol photons-1
    LST = data.sim[[i]]$data.canopy[['LST']] ## units in K
    emis = data.sim[[i]]$data.canopy[['emis']] ##  no units

    data.vegetation <-cbind(n.sim,Photosintesis, Electron_transport,NPQ_energy,NPQ_photon,LST,emis)
    matrix.vegetation[i,] <- data.vegetation

  }
  df.vegetation <- as.data.frame(matrix.vegetation)
  # Set column names as n1, n2, n3, ...
  colnames(df.vegetation) <-  c('n.sim','A','Ja','ENPQ','PNPQ','LST','emis')


  data.table::fwrite(df.vegetation, paste(folder_out,"/vegatation.csv",sep=''))

  df.vegatation.units <-data.frame(Photosintesis = 'umol m-2 s-1', Electron_transport = 'umol m-2 s-1',
                                   NPQ_energy = 'W m-2',  NPQ_photon = 'umol photons-1',
                                  LST = 'Kelvin', emis = '--')
  # save using data.table
  data.table::fwrite(df.vegatation.units, paste(folder_out,"/vegatation_units.csv",sep=''))

  ##############################################################################################################################
  # 1.8 Get Sigma Fluorescence values  ----
  ##############################################################################################################################


  if (get.outputs == 'ALL' | get.outputs == 'Main'){

    matrix.sigmaF <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$sigmaF)
    wlF <- data.sim[[1]]$data.spectral$wlF
    # save using data.table
    data.table::fwrite(data.frame(t(matrix.sigmaF)), paste(folder_out,"/SigmaF.csv",sep=''))
  }



  if (get.plots == T & get.outputs == 'ALL' ) {


    # get the rows for plotting

    if (ncol(matrix.sigmaF) >= 100){
      ## select rows
      n.cols <- 50
      cols.selected <- sample(ncol(matrix.sigmaF), n.cols)


    } else {
      ## select rows
      n.cols <- 5
      cols.selected <- 1:ncol(matrix.sigmaF)
    }

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get sigmaF ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_sigmaF_ <-data.frame(matrix.sigmaF[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_sigmaF_
    df_sigmaF_$wave <- rep(wave, nrow(df_sigmaF_) / length(wave))

    # Plot all spectra in a single plot
    plot.sigmaF_ <-ggplot(df_sigmaF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("sigmaF") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'4-SigmaFluorescence.png',sep=''),plot=plot.sigmaF_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }

  ##############################################################################################################################
  # 1.8 Get Hemispherically Integrated upwelling radiance or TOC upward radiation  (W m-2 um-1)   ----
  ##############################################################################################################################


  if (get.outputs == 'ALL' | get.outputs == 'Main'){

    matrix.Eout_ <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Eout_[1:2001])
    wlS <- data.sim[[i]]$data.spectral$wlS[1:2001]
    # save using data.table
    data.table::fwrite(data.frame(t(matrix.Eout_)), paste(folder_out,"/Eout_spectrum.csv",sep=''))
  }

  if (get.plots == T ) {

    # get the rows for plotting

    if (ncol(matrix.Eout_) >= 100){
      ## select rows
      n.cols <- 50
      cols.selected <- sample(ncol(matrix.Eout_), n.cols)


    } else {
      ## select rows
      n.cols <- 5
      cols.selected <- 1:ncol(matrix.Eout_)
    }

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get Eout_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Eout_ <-data.frame(matrix.Eout_[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlS
    # Add wave column to df_Eout_
    df_Eout_$wave <- rep(wave, nrow(df_Eout_) / length(wave))

    # Plot all spectra in a single plot
    plot.Eout_ <-ggplot(df_Eout_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2500) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'5-Hemispherically_Integrated_upwelling_radiance.png',sep=''),plot=plot.Eout_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }


  ##############################################################################################################################
  # 1.9 Get Fluxes  ----
  ##############################################################################################################################


  df.fluxes <- as.data.frame(t(unlist(data.sim[[1]]$data.fluxes)))
  matrix.fluxes<- matrix(nrow = length(data.sim), ncol = dim(df.fluxes)[2])


  for (i in 1:length(data.sim)) {

    fluxes<- unlist(data.sim[[i]]$data.fluxes)
    matrix.fluxes[i,] <- fluxes

  }
  df.fluxes <- as.data.frame(matrix.fluxes)
  var.names <-names(fluxes)
  n.sim<-c(1:length(data.sim))
  df.fluxes<-cbind(n.sim,df.fluxes)
  # Set column names as n1, n2, n3, ...
  colnames(df.fluxes) <- c("n.sim", var.names)

  # save using data.table
  data.table::fwrite(df.fluxes, paste(folder_out,"/fluxes.csv",sep=''))


  df.fluxes.units<-data.frame( Rnctot = 'W m-2', lEctot = 'W m-2', Hctot = 'W m-2', Actot = 'umol m-2 s-1',
    Tcave = 'C', Rnstot = 'W m-2',  lEstot = 'W m-2', Hstot= 'W m-2',
    Gtot= 'W m-2', Tsave = 'C',Rntot = 'W m-2', lEtot ='W m-2',
    Htot ='W m-2')
  # save using data.table
  data.table::fwrite(df.fluxes.units, paste(folder_out,"/fluxes_units.csv",sep=''))


  ##############################################################################################################################
  # 1.10 Get fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################



  if (get.outputs == 'ALL' | get.outputs == 'Main') {

    wlF <- data.sim[[1]]$data.spectral$wlF

    matrix.LoF_ <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$LoF_)
    matrix.LoF_sunlit <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$LoF_sunlit)
    matrix.LoF_shaded <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$LoF_shaded)
    matrix.LoF_scattered <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$LoF_scattered)
    matrix.LoF_soil <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$LoF_soil)

    matrix.Femliave_ <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$Femliave_)
    matrix.EoutF_ <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$EoutF_)
    matrix.EoutFrc_ <- sapply(seq_along(data.sim), function(i) data.sim[[i]]$data.rad$EoutFrc_)

    # save using data.table
    data.table::fwrite(data.frame(t(matrix.LoF_)), paste(folder_out,"/fluorescence.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.LoF_sunlit)), paste(folder_out,"/fluorescence_sunlit.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.LoF_shaded)), paste(folder_out,"/fluorescence_shaded.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.LoF_scattered)), paste(folder_out,"/fluorescence_scattered.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.LoF_soil)), paste(folder_out,"/fluorescence_soil.csv",sep=''))

    data.table::fwrite(data.frame(t(matrix.Femliave_)), paste(folder_out,"/fluorescence_All_Leaves.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.EoutF_)), paste(folder_out,"/fluorescence_hemis.csv",sep=''))
    data.table::fwrite(data.frame(t(matrix.EoutFrc_)), paste(folder_out,"/fluorescence_ReabsCorr.csv",sep=''))


  }


  if (get.plots == T) {


    # get the rows for plotting

    if (ncol(matrix.LoF_) >= 100){
      ## select rows
      n.cols <- 50
      cols.selected <- sample(ncol(matrix.LoF_), n.cols)


    } else {
      ## select rows
      n.cols <- 5
      cols.selected <- 1:ncol(matrix.LoF_)
    }

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get df.LoF_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Define custom colors for the legend
    colors <- c("red", "blue", "green")  # You can modify the colors as needed


    # Reshape the data frame into a long format
    df_LoF_ <-data.frame(matrix.LoF_[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_LoF_
    df_LoF_$wave <- rep(wave, nrow(df_LoF_) / length(wave))

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))

    #print(plot.LoF_)
    ggsave(paste(folder_for_plots,'6-fluorescence.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.LoF_sunlit ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_sunlit <-data.frame(matrix.LoF_sunlit[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_LoF_sunlit
    df_LoF_sunlit$wave <- rep(wave, nrow(df_LoF_sunlit) / length(wave))

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_sunlit, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence sunlit") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_sunlit.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.LoF_shaded ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_shaded <-data.frame(matrix.LoF_shaded[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_LoF_shaded
    df_LoF_shaded$wave <- rep(wave, nrow(df_LoF_shaded) / length(wave))

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_shaded, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence shaded") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_shaded.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.3 Get df.LoF_scattered ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_scattered <-data.frame(matrix.LoF_scattered[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_LoF_scattered
    df_LoF_scattered$wave <- rep(wave, nrow(df_LoF_scattered) / length(wave))

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_scattered, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence scattered") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_scattered.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")
    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.4 Get df.LoF_soil ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_soil <-data.frame(matrix.LoF_soil[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_LoF_soil
    df_LoF_soil$wave <- rep(wave, nrow(df_LoF_soil) / length(wave))

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_soil, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence soil") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_soil.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.5 Get df.Femliave_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Femliave_ <-data.frame(matrix.Femliave_[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_Femliave_
    df_Femliave_$wave <- rep(wave, nrow(df_Femliave_) / length(wave))


    # Plot all spectra in a single plot
    plot.Femliave_ <-ggplot(df_Femliave_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))

    ggsave(paste(folder_for_plots,'6-fluorescence_AllLeaves.png',sep=''),plot=plot.Femliave_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.EoutF_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_EoutF_ <-data.frame(matrix.EoutF_[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_EoutF_
    df_EoutF_$wave <- rep(wave, nrow(df_EoutF_) / length(wave))

    # Plot all spectra in a single plot
    plot.EoutF_ <-ggplot(df_EoutF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_hemis.png',sep=''),plot=plot.EoutF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.6 Get df.EoutFrc_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_EoutFrc_ <-data.frame(matrix.EoutFrc_[,cols.selected]) %>%
      gather(n.sim,value)
    wave <- wlF
    # Add wave column to df_EoutFrc_
    df_EoutFrc_$wave <- rep(wave, nrow(df_EoutFrc_) / length(wave))

    # Plot all spectra in a single plot
    plot.EoutFrc_ <-ggplot(df_EoutFrc_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_ReabsCorr.png',sep=''),plot=plot.EoutFrc_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }


  ##############################################################################################################################
  # 1.10 Get fluorescence scalar values     ----
  ##############################################################################################################################


  matrix.scalar<- matrix(nrow = length(data.sim), ncol = 10)

  for (i in 1:length(data.sim)) {

    n.sim <- i
    F_1stPeak = data.sim[[i]]$data.rad[['F685']]
    wl_1stPeak = data.sim[[i]]$data.rad[['wl685']]
    F_2ndPeak = data.sim[[i]]$data.rad[['F740']]
    wl_2ndPeak = data.sim[[i]]$data.rad[['wl740']]
    F684 = data.sim[[i]]$data.rad[['F684']]
    F761 = data.sim[[i]]$data.rad[['F761']]
    LFtot = data.sim[[i]]$data.rad[['LoutF']]
    EFtot = data.sim[[i]]$data.rad[['EoutF']]
    EFtot_RC = data.sim[[i]]$data.rad[['EoutFrc']]


    data.scalar <-cbind(n.sim,F_1stPeak, wl_1stPeak,F_2ndPeak,wl_2ndPeak,
                        F684,F761,LFtot,EFtot,EFtot_RC)
    matrix.scalar[i,] <- data.scalar

  }
  df.scalar <- as.data.frame(matrix.scalar)
  # Set column names as n1, n2, n3, ...
  colnames(df.scalar) <- c('n.sim','F685','wl685','F740','wl740','F684','F761','LoutF','EoutF','EoutFrc')

  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar.csv",sep=''))

  df.scalar.units<-data.frame( F685 = 'W m-2 um-1 sr-1', wl685 = 'nm',
                               F740 = 'W m-2 um-1 sr-1', wl740 = 'nm',
                               F684 = 'W m-2 um-1 sr-1', F761 = 'W m-2 um-1 sr-1',
                               LFtot= 'W m-2 sr-1',EFtot = 'W m-2', EFtot_RC ='W m-2')
  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar_units.csv",sep=''))





}


